### Criar item
POST http://127.0.0.1:8000/items
Content-Type: application/json

{
  "name": "Livro de Terror"
}

###

### Listar todos os itens
GET http://127.0.0.1:8000/items

###

### Atualizar item (substitua pelo UUID retornado no POST)
PUT http://127.0.0.1:8000/items/b4a59aaa-77df-48d2-994c-8c5b18a9b321
Content-Type: application/json

{
  "name": "Livro de Receitas Atualizado"
}

###

### Deletar item (substitua pelo UUID retornado no POST)
DELETE http://127.0.0.1:8000/items/b4a59aaa-77df-48d2-994c-8c5b18a9b321
